kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: $APP_NAME
  namespace: $NAME_SPACE
  labels:
    app: $APP_NAME
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: >-
    image-registry.openshift-image-registry.svc:5000/$NAME_SPACE/$APP_NAME
  tags:
    - tag: latest