parameters:
  - name: gradleContainer
    type: string
    default: 'gradle:8.10.1-jdk21'
  - name: sonarContainer
    type: string
    default: 'sonarsource/sonar-scanner-cli@sha256:494ecc3b5b1ee1625bd377b3905c4284e4f0cc155cff397805a244dee1c7d575'  # SonarQube scanner container
  - name: cliSources
    type: string
    default: '.'
  - name: configFile
    type: string
    default: 'deployment/sonar-project.properties'
stages:
  - stage: SonarAnalysis
    jobs:
      - job: BuildAndAnalyze
        displayName: 'Build and Analyze'
        pool:
          vmImage: ubuntu-20.04
        steps:
          - checkout: self
          - script: |
              TARGET_FILE="${{ parameters.configFile }}"
              if [ -f "$TARGET_FILE" ]
              then
                  echo "$TARGET_FILE existe"
              else
                  echo "el archivo de configuracion de sonar: $TARGET_FILE no existe."
                  exit 1
              fi
            displayName: 'Check Sonar config file'
          - script: |
              echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                            https://maven.apache.org/xsd/settings-1.0.0.xsd">
                <mirrors>
                  <mirror>
                    <id>mirrorId</id>
                    <mirrorOf>*</mirrorOf>
                    <url>https://apicore.segurossura.com.mx/nexus/repository/maven-internal-and-public-group/</url>
                  </mirror>
                </mirrors>
              </settings>' > settings.xml
              
              pwd
              
              docker run --rm \
                -v "$(Build.SourcesDirectory):/home/gradle/project" \
                -v "$(Build.SourcesDirectory)/.gradle:/home/gradle/.gradle" \
                -v "$(pwd)/settings.xml:/home/gradle/.m2/settings.xml" \
                -w /home/gradle/project \
                ${{ parameters.gradleContainer }} \
                gradle build -x test --info
            displayName: 'Gradle Build'
          - script: |
              docker run --rm \
                -v "$(Build.SourcesDirectory):/home/gradle/project" \
                -v "$(Build.SourcesDirectory)/.gradle:/home/gradle/.gradle" \
                -v "$(pwd)/settings.xml:/home/gradle/.m2/settings.xml" \
                -w /home/gradle/project \
                ${{ parameters.gradleContainer }} \
                gradle jacocoMergedReport
            displayName: 'Generate JaCoCo Report'
          - script: |
              docker run --rm \
                -e SONAR_HOST_URL="https://segurossura-nginx.azurewebsites.net" \
                -e SONAR_LOGIN="099cac0f944c7eedbc9b4e0511bfebecdc0b7b47" \
                -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=$(Build.Repository.Name) -Dsonar.qualitygate.wait=true" \
                -v "$(Build.SourcesDirectory):/usr/src" \
                -v "$(Build.SourcesDirectory)/.gradle/caches/modules-2/files-2.1/org.projectlombok/lombok/1.18.32/17d46b3e205515e1e8efd3ee4d57ce8018914163/lombok-1.18.32.jar:/usr/src/caches/org.projectlombok/lombok/1.18.32/lombok-1.18.32.jar" \
                -w /usr/src \
                ${{ parameters.sonarContainer }} \
                sonar-scanner -Dproject.settings=deployment/sonar-project.properties
            displayName: 'SonarQubeAnalyze'